export  default {
 data: [
   {text: 'How to make a bulb from scratch', description: 'Making bulb from scratch using the element of true and valuables'},
   {text: 'Translation Support Services', description: 'Administrative and Translation Support Services'},
   {text: 'Business Sector-Specific Strategy', description: 'Business Sector-Specific Strategy Consulting'},
   {text: 'Angel Investment and Start-Up', description: 'This is a special case'},
   {text: 'Creative Arts, Media, Design', description: 'Creative Arts, Media, Design and Communication Services'},
   {text: 'Executive, Leadership, Life, Productivity', description: 'Executive, Leadership, Life, Productivity and Career Coaching, Mentorship and Training'},
   {text: 'Career Coaching, Mentorship and Training', description: 'Executive, Leadership, Life, Productivity and Career Coaching, Mentorship and Training'},
   {text: 'Human Resources and Recruitment Consulting', description: 'Human Resources and Recruitment Consulting'},
   {text: 'Nonprofit, International Development', description: 'Nonprofit, International Development, Grant Writing and Social Impact Consulting'},
   {text: 'Programming & IT Services', description: 'Programming & IT Services'},
   {text: 'Grant Writing and Social Impact', description: 'Programming & IT Services'},
   {text: 'Technology and Telecom Consulting', description: 'Technology and Telecom Consulting'},
   {text: 'Venture Capital', description: 'Venture Capital, Angel Investment and Start-Up Consulting'},
   {text:  'Career Coach', description: 'Career Coach'},
  {text: 'Business Coach', description: 'Business Coach'},
  {text: 'Corporate Consultant', description: 'Corporate Consultant'},
  {text: 'Technology Expert', description: 'Technology Expert'},
  {text: 'Investment Advisor', description: 'Investment Advisor'},
  {text: 'Political Advisor', description: 'Political Advisor'},
  {text: 'Subject Expert', description: 'Subject Expert'},
  {text: 'Start-Up Coach', description: 'Start-Up Coach'},
  {text: 'Executive Coach', description: 'Executive Coach'},
  {text: 'Life Coach', description: 'Life Coach'},
  {text: 'Mentor', description: 'Mentor'},
  {text: 'Retreat Facilitator', description: 'Retreat Facilitator'},
  {text: 'Board Member', description: 'Board Member'},
  {text: 'Speaker', description: 'Speaker'},
  {text: 'Productivity Coach', description: 'Productivity Coach'},
  {text: 'Academic Advisor', description: 'Academic Advisor'},
 ]
};
